command_timeout = 2000

# [directory]
# truncate_to_repo = false
# truncation_length = 2
# truncation_symbol = "…/" 

[nodejs]
disabled = false

[python]
disabled = false

[aws]
disabled = true

[ruby]
detect_variables = []
